# Fine-tune an LM on the enron text dataset.

dataset_args:
  dataset_path: ../src/pii_leakage/extern/echr
  dataset_mode: undefended
  sample_duplication_rate: 1

trainer_args:
  save_steps: 1000
  callback_after_n_steps: 1000
  num_train_epochs: 4
  gradient_accumulation_steps: 8
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 2
  # resume_from_checkpoint: True
  output_dir: ./experiments/test_check


privacy_args:
  target_epsilon: 8
  max_grad_norm_dp: 1.0

model_args:
  architecture: gpt2
  pre_trained: True   # Start from a pre-trained checkpoint

ner_args:
  ner: flair
  ner_model: flair/ner-english-ontonotes-large
  anon_token: <MASK>
  anonymize: False
